version: '2'
services:
  ghost:
    ports:
      - "2368:2368"
  nginx:
    volumes:
      - ./sites-enabled/dev:/sites-enabled
      - ./conf:/conf.d
      - ./log:/var/log/nginx
      - ./certs:/certs

