version: '2'
services:
  ghost:
    image: ghost:0.9.0
    container_name: ghost
    restart: always
  nginx:
    image: wonderfall/nginx:latest
    container_name: nginx
    links:
      - ghost
    ports:
      - "8080:8000"
      - "443:4430"
    restart: always
